runtime: python39
api_version: 1
threadsafe: true

handlers:
- url: /
  script: main.app

- url: /index\.html
  script: main.app

- url: /stylesheets
  static_dir: static/css

- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$

- url: /.*
  script: main.app