runtime: python39
threadsafe: true

handlers:
- url: /templates
  static_dir: static/css
  templates_dir: templates/
- url: http://127.0.0.1:5000/
  script: main.app

libraries:
- name: ssl
  version: "2.7.11"
